#!/bin/sh

PUKIWIKI_ROOT='/home/niwacchi/public_html/wiki'

cd $PUKIWIKI_ROOT

chmod 755 ./
chmod 644 .htaccess
chmod 644 en.lng.php
chmod 644 ja.lng.php
chmod 644 default.ini.php
chmod 644 index.php
chmod 644 keitai.ini.php
chmod 644 pukiwiki.ini.php
chmod 644 rules.ini.php
chmod 777 ./attach 
chmod 644 ./attach/.htaccess
chmod 644 ./attach/index.html
chmod 777 ./backup 
chmod 644 ./backup/.htaccess
chmod 644 ./backup/index.html
chmod 777 ./cache 
chmod 666 ./cache/recent.dat
chmod 666 ./cache/autolink.dat
chmod 666 ./cache/entities.dat
chmod 666 ./cache/*.ref
chmod 666 ./cache/*.rel
chmod 644 ./cache/.htaccess
chmod 644 ./cache/index.html
chmod 777 ./counter/
chmod 644 ./counter/.htaccess
chmod 644 ./counter/index.html
chmod 777 ./diff 
chmod 644 ./diff/.htaccess
chmod 644 ./diff/index.html
chmod 755 ./image 
chmod 644 ./image/index.html
chmod 644 ./image/add.png
chmod 644 ./image/backup.png
chmod 644 ./image/copy.png
chmod 644 ./image/diff.png
chmod 644 ./image/edit.png
chmod 644 ./image/file.png
chmod 644 ./image/freeze.png
chmod 644 ./image/help.png
chmod 644 ./image/list.png
chmod 644 ./image/new.png
chmod 644 ./image/noimage.png
chmod 644 ./image/pukiwiki.gif
chmod 644 ./image/pukiwiki.png
chmod 644 ./image/rdf.png
chmod 644 ./image/recentchanges.png
chmod 644 ./image/reload.png
chmod 644 ./image/rename.png
chmod 644 ./image/rss.png
chmod 644 ./image/rss20.png
chmod 644 ./image/search.png
chmod 644 ./image/top.png
chmod 644 ./image/unfreeze.png
chmod 755 ./image/face 
chmod 644 ./image/face/index.html
chmod 644 ./image/face/bigsmile.png
chmod 644 ./image/face/heart.png
chmod 644 ./image/face/huh.png
chmod 644 ./image/face/oh.png
chmod 644 ./image/face/sad.png
chmod 644 ./image/face/smile.png
chmod 644 ./image/face/wink.png
chmod 644 ./image/face/worried.png
chmod 755 ./lib 
chmod 644 ./lib/.htaccess
chmod 644 ./lib/index.html
chmod 644 ./lib/auth.php
chmod 644 ./lib/backup.php
chmod 644 ./lib/config.php
chmod 644 ./lib/convert_html.php
chmod 644 ./lib/diff.php
chmod 644 ./lib/file.php
chmod 644 ./lib/func.php
chmod 644 ./lib/html.php
chmod 644 ./lib/init.php
chmod 644 ./lib/link.php
chmod 644 ./lib/mail.php
chmod 644 ./lib/make_link.php
chmod 644 ./lib/mbstring.php
chmod 644 ./lib/plugin.php
chmod 644 ./lib/proxy.php
chmod 644 ./lib/pukiwiki.php
chmod 644 ./lib/trackback.php
chmod 755 ./plugin 
chmod 644 ./plugin/.htaccess
chmod 644 ./plugin/index.html
chmod 644 ./plugin/add.inc.php
chmod 644 ./plugin/amazon.inc.php
chmod 644 ./plugin/aname.inc.php
chmod 644 ./plugin/article.inc.php
chmod 644 ./plugin/attach.inc.php
chmod 644 ./plugin/back.inc.php
chmod 644 ./plugin/backup.inc.php
chmod 644 ./plugin/br.inc.php
chmod 644 ./plugin/bugtrack.inc.php
chmod 644 ./plugin/bugtrack_list.inc.php
chmod 644 ./plugin/calendar.inc.php
chmod 644 ./plugin/calendar_edit.inc.php
chmod 644 ./plugin/calendar_read.inc.php
chmod 644 ./plugin/calendar_viewer.inc.php
chmod 644 ./plugin/calendar2.inc.php
chmod 644 ./plugin/clear.inc.php
chmod 644 ./plugin/color.inc.php
chmod 644 ./plugin/comment.inc.php
chmod 644 ./plugin/contents.inc.php
chmod 644 ./plugin/counter.inc.php
chmod 644 ./plugin/deleted.inc.php
chmod 644 ./plugin/diff.inc.php
chmod 644 ./plugin/dump.inc.php
chmod 644 ./plugin/edit.inc.php
chmod 644 ./plugin/filelist.inc.php
chmod 644 ./plugin/freeze.inc.php
chmod 644 ./plugin/hr.inc.php
chmod 644 ./plugin/img.inc.php
chmod 644 ./plugin/include.inc.php
chmod 644 ./plugin/includesubmenu.inc.php
chmod 644 ./plugin/insert.inc.php
chmod 644 ./plugin/interwiki.inc.php
chmod 644 ./plugin/links.inc.php
chmod 644 ./plugin/list.inc.php
chmod 644 ./plugin/lookup.inc.php
chmod 644 ./plugin/ls.inc.php
chmod 644 ./plugin/ls2.inc.php
chmod 644 ./plugin/map.inc.php
chmod 644 ./plugin/md5.inc.php
chmod 644 ./plugin/memo.inc.php
chmod 644 ./plugin/menu.inc.php
chmod 644 ./plugin/navi.inc.php
chmod 644 ./plugin/new.inc.php
chmod 644 ./plugin/newpage.inc.php
chmod 644 ./plugin/nofollow.inc.php
chmod 644 ./plugin/norelated.inc.php
chmod 644 ./plugin/online.inc.php
chmod 644 ./plugin/paint.inc.php
chmod 644 ./plugin/pcomment.inc.php
chmod 644 ./plugin/popular.inc.php
chmod 644 ./plugin/random.inc.php
chmod 644 ./plugin/read.inc.php
chmod 644 ./plugin/recent.inc.php
chmod 644 ./plugin/ref.inc.php
chmod 644 ./plugin/referer.inc.php
chmod 644 ./plugin/related.inc.php
chmod 644 ./plugin/rename.inc.php
chmod 644 ./plugin/rss.inc.php
chmod 644 ./plugin/rss10.inc.php
chmod 644 ./plugin/ruby.inc.php
chmod 644 ./plugin/search.inc.php
chmod 644 ./plugin/server.inc.php
chmod 644 ./plugin/setlinebreak.inc.php
chmod 644 ./plugin/showrss.inc.php
chmod 644 ./plugin/size.inc.php
chmod 644 ./plugin/source.inc.php
chmod 644 ./plugin/tb.inc.php
chmod 644 ./plugin/template.inc.php
chmod 644 ./plugin/topicpath.inc.php
chmod 644 ./plugin/touchgraph.inc.php
chmod 644 ./plugin/tracker.inc.php
chmod 644 ./plugin/tracker_list.inc.php
chmod 644 ./plugin/unfreeze.inc.php
chmod 644 ./plugin/update_entities.inc.php
chmod 644 ./plugin/version.inc.php
chmod 644 ./plugin/versionlist.inc.php
chmod 644 ./plugin/vote.inc.php
chmod 644 ./plugin/yetlist.inc.php
chmod 755 ./skin 
chmod 644 ./skin/pukiwiki.css.php
chmod 644 ./skin/.htaccess
chmod 644 ./skin/index.html
chmod 644 ./skin/keitai.skin.php
chmod 644 ./skin/pukiwiki.skin.php
chmod 644 ./skin/tdiary.css.php
chmod 644 ./skin/tdiary.skin.php
chmod 777 ./trackback 
chmod 644 ./trackback/.htaccess
chmod 644 ./trackback/index.html
chmod 777 ./wiki 
chmod 644 ./wiki/.htaccess
chmod 644 ./wiki/index.html
chmod 666 ./wiki/*.txt
chmod 777 ./wiki.en 
chmod 644 ./wiki.en/.htaccess
chmod 644 ./wiki.en/index.html
chmod 666 ./wiki.en/*.txt

